namespace: inference-demo

resources:
  - ../base

patches:
- target:
    kind: Deployment
    name: rhaiis
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --model=/model/llama31-8b
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --served-model-name=Meta-Llama-3.1-8B-Instruct-quantized.w4a16 
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --gpu-memory-utilization=0.92
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --max-model-len=62320
