apiVersion: apps/v1
kind: Deployment
metadata:
  name: granite
  labels:
    app: granite
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: granite
  template:
    metadata:
      labels:
        app: granite
    spec:
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: models
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
      serviceAccountName: default
      containers:
        - name: granite
          image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9:latest'
          imagePullPolicy: IfNotPresent
          env:
            - name: VLLM_SERVER_DEV_MODE
              value: '1'
          command:
            - python
            - '-m'
            - vllm.entrypoints.openai.api_server
          args:
            - '--port=8000'
            - '--model=/model'
            - '--served-model-name=granite-3.1-8b-instruct-quantized.w4a16'
            - '--tensor-parallel-size=1'
            - '--max-model-len=50000'
            - '--dtype=auto'
            - '--gpu-memory-utilization=0.90'
          resources:
            limits:
              cpu: '10'
              nvidia.com/gpu: '1'
              memory: 16Gi
            requests:
              cpu: '1'
              memory: 6Gi
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: model-volume
              mountPath: /model
            - name: shm
              mountPath: /dev/shm 
      restartPolicy: Always