namespace: inference-demo

resources:
  - ../base

patches:
- target:
    kind: Deployment
    name: rhaiis
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --model=/model/granite31-8b
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --served-model-name=granite-3.1-8b-instruct-quantized.w4a16
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --max-model-len=59520
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-auto-tool-choice
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --tool-call-parser=granite