kind: Service
apiVersion: v1
metadata:
  labels:
    metrics: workload-monitor
  name: rhaiis
spec:
  ports:
    - name: rhaiis
      protocol: TCP
      port: 80
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: rhaiis
