kind: Service
apiVersion: v1
metadata:
  labels:
    metrics: 'true'
  name: granite
spec:
  ports:
    - name: granite
      protocol: TCP
      port: 80
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: granite
