kind: Secret
apiVersion: v1
metadata:
  name: granite-config
  annotations:
    openshift.io/description: Connect to a granite model
    openshift.io/display-name: Self-Hosted Granite on OCP
stringData:
  DISABLE_TELEMETRY: "true"
  GENERIC_OPEN_AI_API_KEY: ""
  GENERIC_OPEN_AI_BASE_PATH: "https://granite-inference-demo.apps.prime.pitt.ca/v1"
  GENERIC_OPEN_AI_MAX_TOKENS: "4096"
  GENERIC_OPEN_AI_MODEL_PREF: "granite-3.1-8b-instruct-quantized.w4a16"
  LLM_PROVIDER: "generic-openai"
  GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT: "8192"
  VECTOR_DB: "lancedb"
  EMBEDDING_ENGINE: "native"
type: Opaque